// Generated by jextract

package kid_meier.libpostal4j.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct libpostal_language_classifier_response {
 *     size_t num_languages;
 *     char **languages;
 *     double *probs;
 * }
 * }
 */
public class libpostal_language_classifier_response {

    libpostal_language_classifier_response() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        libpostal_h.C_LONG.withName("num_languages"),
        libpostal_h.C_POINTER.withName("languages"),
        libpostal_h.C_POINTER.withName("probs")
    ).withName("libpostal_language_classifier_response");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong num_languages$LAYOUT = (OfLong)$LAYOUT.select(groupElement("num_languages"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t num_languages
     * }
     */
    public static final OfLong num_languages$layout() {
        return num_languages$LAYOUT;
    }

    private static final long num_languages$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t num_languages
     * }
     */
    public static final long num_languages$offset() {
        return num_languages$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t num_languages
     * }
     */
    public static long num_languages(MemorySegment struct) {
        return struct.get(num_languages$LAYOUT, num_languages$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t num_languages
     * }
     */
    public static void num_languages(MemorySegment struct, long fieldValue) {
        struct.set(num_languages$LAYOUT, num_languages$OFFSET, fieldValue);
    }

    private static final AddressLayout languages$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("languages"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char **languages
     * }
     */
    public static final AddressLayout languages$layout() {
        return languages$LAYOUT;
    }

    private static final long languages$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char **languages
     * }
     */
    public static final long languages$offset() {
        return languages$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char **languages
     * }
     */
    public static MemorySegment languages(MemorySegment struct) {
        return struct.get(languages$LAYOUT, languages$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char **languages
     * }
     */
    public static void languages(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(languages$LAYOUT, languages$OFFSET, fieldValue);
    }

    private static final AddressLayout probs$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("probs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double *probs
     * }
     */
    public static final AddressLayout probs$layout() {
        return probs$LAYOUT;
    }

    private static final long probs$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double *probs
     * }
     */
    public static final long probs$offset() {
        return probs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double *probs
     * }
     */
    public static MemorySegment probs(MemorySegment struct) {
        return struct.get(probs$LAYOUT, probs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double *probs
     * }
     */
    public static void probs(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(probs$LAYOUT, probs$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

