// Generated by jextract

package kid_meier.libpostal4j.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct libpostal_fuzzy_duplicate_status {
 *     libpostal_duplicate_status_t status;
 *     double similarity;
 * }
 * }
 */
public class libpostal_fuzzy_duplicate_status {

    libpostal_fuzzy_duplicate_status() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        libpostal_h.C_INT.withName("status"),
        MemoryLayout.paddingLayout(4),
        libpostal_h.C_DOUBLE.withName("similarity")
    ).withName("libpostal_fuzzy_duplicate_status");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt status$LAYOUT = (OfInt)$LAYOUT.select(groupElement("status"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * libpostal_duplicate_status_t status
     * }
     */
    public static final OfInt status$layout() {
        return status$LAYOUT;
    }

    private static final long status$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * libpostal_duplicate_status_t status
     * }
     */
    public static final long status$offset() {
        return status$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * libpostal_duplicate_status_t status
     * }
     */
    public static int status(MemorySegment struct) {
        return struct.get(status$LAYOUT, status$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * libpostal_duplicate_status_t status
     * }
     */
    public static void status(MemorySegment struct, int fieldValue) {
        struct.set(status$LAYOUT, status$OFFSET, fieldValue);
    }

    private static final OfDouble similarity$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("similarity"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double similarity
     * }
     */
    public static final OfDouble similarity$layout() {
        return similarity$LAYOUT;
    }

    private static final long similarity$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double similarity
     * }
     */
    public static final long similarity$offset() {
        return similarity$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double similarity
     * }
     */
    public static double similarity(MemorySegment struct) {
        return struct.get(similarity$LAYOUT, similarity$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double similarity
     * }
     */
    public static void similarity(MemorySegment struct, double fieldValue) {
        struct.set(similarity$LAYOUT, similarity$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

