// Generated by jextract

package kid_meier.libpostal4j.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct libpostal_near_dupe_hash_options {
 *     _Bool with_name;
 *     _Bool with_address;
 *     _Bool with_unit;
 *     _Bool with_city_or_equivalent;
 *     _Bool with_small_containing_boundaries;
 *     _Bool with_postal_code;
 *     _Bool with_latlon;
 *     double latitude;
 *     double longitude;
 *     uint32_t geohash_precision;
 *     _Bool name_and_address_keys;
 *     _Bool name_only_keys;
 *     _Bool address_only_keys;
 * } libpostal_near_dupe_hash_options_t
 * }
 */
public class libpostal_near_dupe_hash_options_t extends libpostal_near_dupe_hash_options {

    libpostal_near_dupe_hash_options_t() {
        // Should not be called directly
    }
}

