// Generated by jextract

package kid_meier.libpostal4j.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct libpostal_fuzzy_duplicate_status {
 *     libpostal_duplicate_status_t status;
 *     double similarity;
 * } libpostal_fuzzy_duplicate_status_t
 * }
 */
public class libpostal_fuzzy_duplicate_status_t extends libpostal_fuzzy_duplicate_status {

    libpostal_fuzzy_duplicate_status_t() {
        // Should not be called directly
    }
}

