// Generated by jextract

package kid_meier.libpostal4j.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct libpostal_language_classifier_response {
 *     size_t num_languages;
 *     char **languages;
 *     double *probs;
 * } libpostal_language_classifier_response_t
 * }
 */
public class libpostal_language_classifier_response_t extends libpostal_language_classifier_response {

    libpostal_language_classifier_response_t() {
        // Should not be called directly
    }
}

