// Generated by jextract

package kid_meier.libpostal4j.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct libpostal_normalized_token {
 *     char *str;
 *     libpostal_token_t token;
 * } libpostal_normalized_token_t
 * }
 */
public class libpostal_normalized_token_t extends libpostal_normalized_token {

    libpostal_normalized_token_t() {
        // Should not be called directly
    }
}

