// Generated by jextract

package kid_meier.libpostal4j.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct libpostal_normalize_options {
 *     char **languages;
 *     size_t num_languages;
 *     uint16_t address_components;
 *     _Bool latin_ascii;
 *     _Bool transliterate;
 *     _Bool strip_accents;
 *     _Bool decompose;
 *     _Bool lowercase;
 *     _Bool trim_string;
 *     _Bool drop_parentheticals;
 *     _Bool replace_numeric_hyphens;
 *     _Bool delete_numeric_hyphens;
 *     _Bool split_alpha_from_numeric;
 *     _Bool replace_word_hyphens;
 *     _Bool delete_word_hyphens;
 *     _Bool delete_final_periods;
 *     _Bool delete_acronym_periods;
 *     _Bool drop_english_possessives;
 *     _Bool delete_apostrophes;
 *     _Bool expand_numex;
 *     _Bool roman_numerals;
 * }
 * }
 */
public class libpostal_normalize_options {

    libpostal_normalize_options() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        libpostal_h.C_POINTER.withName("languages"),
        libpostal_h.C_LONG.withName("num_languages"),
        libpostal_h.C_SHORT.withName("address_components"),
        libpostal_h.C_BOOL.withName("latin_ascii"),
        libpostal_h.C_BOOL.withName("transliterate"),
        libpostal_h.C_BOOL.withName("strip_accents"),
        libpostal_h.C_BOOL.withName("decompose"),
        libpostal_h.C_BOOL.withName("lowercase"),
        libpostal_h.C_BOOL.withName("trim_string"),
        libpostal_h.C_BOOL.withName("drop_parentheticals"),
        libpostal_h.C_BOOL.withName("replace_numeric_hyphens"),
        libpostal_h.C_BOOL.withName("delete_numeric_hyphens"),
        libpostal_h.C_BOOL.withName("split_alpha_from_numeric"),
        libpostal_h.C_BOOL.withName("replace_word_hyphens"),
        libpostal_h.C_BOOL.withName("delete_word_hyphens"),
        libpostal_h.C_BOOL.withName("delete_final_periods"),
        libpostal_h.C_BOOL.withName("delete_acronym_periods"),
        libpostal_h.C_BOOL.withName("drop_english_possessives"),
        libpostal_h.C_BOOL.withName("delete_apostrophes"),
        libpostal_h.C_BOOL.withName("expand_numex"),
        libpostal_h.C_BOOL.withName("roman_numerals"),
        MemoryLayout.paddingLayout(4)
    ).withName("libpostal_normalize_options");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout languages$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("languages"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char **languages
     * }
     */
    public static final AddressLayout languages$layout() {
        return languages$LAYOUT;
    }

    private static final long languages$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char **languages
     * }
     */
    public static final long languages$offset() {
        return languages$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char **languages
     * }
     */
    public static MemorySegment languages(MemorySegment struct) {
        return struct.get(languages$LAYOUT, languages$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char **languages
     * }
     */
    public static void languages(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(languages$LAYOUT, languages$OFFSET, fieldValue);
    }

    private static final OfLong num_languages$LAYOUT = (OfLong)$LAYOUT.select(groupElement("num_languages"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t num_languages
     * }
     */
    public static final OfLong num_languages$layout() {
        return num_languages$LAYOUT;
    }

    private static final long num_languages$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t num_languages
     * }
     */
    public static final long num_languages$offset() {
        return num_languages$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t num_languages
     * }
     */
    public static long num_languages(MemorySegment struct) {
        return struct.get(num_languages$LAYOUT, num_languages$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t num_languages
     * }
     */
    public static void num_languages(MemorySegment struct, long fieldValue) {
        struct.set(num_languages$LAYOUT, num_languages$OFFSET, fieldValue);
    }

    private static final OfShort address_components$LAYOUT = (OfShort)$LAYOUT.select(groupElement("address_components"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint16_t address_components
     * }
     */
    public static final OfShort address_components$layout() {
        return address_components$LAYOUT;
    }

    private static final long address_components$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint16_t address_components
     * }
     */
    public static final long address_components$offset() {
        return address_components$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint16_t address_components
     * }
     */
    public static short address_components(MemorySegment struct) {
        return struct.get(address_components$LAYOUT, address_components$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint16_t address_components
     * }
     */
    public static void address_components(MemorySegment struct, short fieldValue) {
        struct.set(address_components$LAYOUT, address_components$OFFSET, fieldValue);
    }

    private static final OfBoolean latin_ascii$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("latin_ascii"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool latin_ascii
     * }
     */
    public static final OfBoolean latin_ascii$layout() {
        return latin_ascii$LAYOUT;
    }

    private static final long latin_ascii$OFFSET = 18;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool latin_ascii
     * }
     */
    public static final long latin_ascii$offset() {
        return latin_ascii$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool latin_ascii
     * }
     */
    public static boolean latin_ascii(MemorySegment struct) {
        return struct.get(latin_ascii$LAYOUT, latin_ascii$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool latin_ascii
     * }
     */
    public static void latin_ascii(MemorySegment struct, boolean fieldValue) {
        struct.set(latin_ascii$LAYOUT, latin_ascii$OFFSET, fieldValue);
    }

    private static final OfBoolean transliterate$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("transliterate"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool transliterate
     * }
     */
    public static final OfBoolean transliterate$layout() {
        return transliterate$LAYOUT;
    }

    private static final long transliterate$OFFSET = 19;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool transliterate
     * }
     */
    public static final long transliterate$offset() {
        return transliterate$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool transliterate
     * }
     */
    public static boolean transliterate(MemorySegment struct) {
        return struct.get(transliterate$LAYOUT, transliterate$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool transliterate
     * }
     */
    public static void transliterate(MemorySegment struct, boolean fieldValue) {
        struct.set(transliterate$LAYOUT, transliterate$OFFSET, fieldValue);
    }

    private static final OfBoolean strip_accents$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("strip_accents"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool strip_accents
     * }
     */
    public static final OfBoolean strip_accents$layout() {
        return strip_accents$LAYOUT;
    }

    private static final long strip_accents$OFFSET = 20;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool strip_accents
     * }
     */
    public static final long strip_accents$offset() {
        return strip_accents$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool strip_accents
     * }
     */
    public static boolean strip_accents(MemorySegment struct) {
        return struct.get(strip_accents$LAYOUT, strip_accents$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool strip_accents
     * }
     */
    public static void strip_accents(MemorySegment struct, boolean fieldValue) {
        struct.set(strip_accents$LAYOUT, strip_accents$OFFSET, fieldValue);
    }

    private static final OfBoolean decompose$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("decompose"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool decompose
     * }
     */
    public static final OfBoolean decompose$layout() {
        return decompose$LAYOUT;
    }

    private static final long decompose$OFFSET = 21;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool decompose
     * }
     */
    public static final long decompose$offset() {
        return decompose$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool decompose
     * }
     */
    public static boolean decompose(MemorySegment struct) {
        return struct.get(decompose$LAYOUT, decompose$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool decompose
     * }
     */
    public static void decompose(MemorySegment struct, boolean fieldValue) {
        struct.set(decompose$LAYOUT, decompose$OFFSET, fieldValue);
    }

    private static final OfBoolean lowercase$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("lowercase"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool lowercase
     * }
     */
    public static final OfBoolean lowercase$layout() {
        return lowercase$LAYOUT;
    }

    private static final long lowercase$OFFSET = 22;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool lowercase
     * }
     */
    public static final long lowercase$offset() {
        return lowercase$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool lowercase
     * }
     */
    public static boolean lowercase(MemorySegment struct) {
        return struct.get(lowercase$LAYOUT, lowercase$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool lowercase
     * }
     */
    public static void lowercase(MemorySegment struct, boolean fieldValue) {
        struct.set(lowercase$LAYOUT, lowercase$OFFSET, fieldValue);
    }

    private static final OfBoolean trim_string$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("trim_string"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool trim_string
     * }
     */
    public static final OfBoolean trim_string$layout() {
        return trim_string$LAYOUT;
    }

    private static final long trim_string$OFFSET = 23;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool trim_string
     * }
     */
    public static final long trim_string$offset() {
        return trim_string$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool trim_string
     * }
     */
    public static boolean trim_string(MemorySegment struct) {
        return struct.get(trim_string$LAYOUT, trim_string$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool trim_string
     * }
     */
    public static void trim_string(MemorySegment struct, boolean fieldValue) {
        struct.set(trim_string$LAYOUT, trim_string$OFFSET, fieldValue);
    }

    private static final OfBoolean drop_parentheticals$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("drop_parentheticals"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool drop_parentheticals
     * }
     */
    public static final OfBoolean drop_parentheticals$layout() {
        return drop_parentheticals$LAYOUT;
    }

    private static final long drop_parentheticals$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool drop_parentheticals
     * }
     */
    public static final long drop_parentheticals$offset() {
        return drop_parentheticals$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool drop_parentheticals
     * }
     */
    public static boolean drop_parentheticals(MemorySegment struct) {
        return struct.get(drop_parentheticals$LAYOUT, drop_parentheticals$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool drop_parentheticals
     * }
     */
    public static void drop_parentheticals(MemorySegment struct, boolean fieldValue) {
        struct.set(drop_parentheticals$LAYOUT, drop_parentheticals$OFFSET, fieldValue);
    }

    private static final OfBoolean replace_numeric_hyphens$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("replace_numeric_hyphens"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool replace_numeric_hyphens
     * }
     */
    public static final OfBoolean replace_numeric_hyphens$layout() {
        return replace_numeric_hyphens$LAYOUT;
    }

    private static final long replace_numeric_hyphens$OFFSET = 25;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool replace_numeric_hyphens
     * }
     */
    public static final long replace_numeric_hyphens$offset() {
        return replace_numeric_hyphens$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool replace_numeric_hyphens
     * }
     */
    public static boolean replace_numeric_hyphens(MemorySegment struct) {
        return struct.get(replace_numeric_hyphens$LAYOUT, replace_numeric_hyphens$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool replace_numeric_hyphens
     * }
     */
    public static void replace_numeric_hyphens(MemorySegment struct, boolean fieldValue) {
        struct.set(replace_numeric_hyphens$LAYOUT, replace_numeric_hyphens$OFFSET, fieldValue);
    }

    private static final OfBoolean delete_numeric_hyphens$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("delete_numeric_hyphens"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool delete_numeric_hyphens
     * }
     */
    public static final OfBoolean delete_numeric_hyphens$layout() {
        return delete_numeric_hyphens$LAYOUT;
    }

    private static final long delete_numeric_hyphens$OFFSET = 26;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool delete_numeric_hyphens
     * }
     */
    public static final long delete_numeric_hyphens$offset() {
        return delete_numeric_hyphens$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool delete_numeric_hyphens
     * }
     */
    public static boolean delete_numeric_hyphens(MemorySegment struct) {
        return struct.get(delete_numeric_hyphens$LAYOUT, delete_numeric_hyphens$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool delete_numeric_hyphens
     * }
     */
    public static void delete_numeric_hyphens(MemorySegment struct, boolean fieldValue) {
        struct.set(delete_numeric_hyphens$LAYOUT, delete_numeric_hyphens$OFFSET, fieldValue);
    }

    private static final OfBoolean split_alpha_from_numeric$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("split_alpha_from_numeric"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool split_alpha_from_numeric
     * }
     */
    public static final OfBoolean split_alpha_from_numeric$layout() {
        return split_alpha_from_numeric$LAYOUT;
    }

    private static final long split_alpha_from_numeric$OFFSET = 27;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool split_alpha_from_numeric
     * }
     */
    public static final long split_alpha_from_numeric$offset() {
        return split_alpha_from_numeric$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool split_alpha_from_numeric
     * }
     */
    public static boolean split_alpha_from_numeric(MemorySegment struct) {
        return struct.get(split_alpha_from_numeric$LAYOUT, split_alpha_from_numeric$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool split_alpha_from_numeric
     * }
     */
    public static void split_alpha_from_numeric(MemorySegment struct, boolean fieldValue) {
        struct.set(split_alpha_from_numeric$LAYOUT, split_alpha_from_numeric$OFFSET, fieldValue);
    }

    private static final OfBoolean replace_word_hyphens$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("replace_word_hyphens"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool replace_word_hyphens
     * }
     */
    public static final OfBoolean replace_word_hyphens$layout() {
        return replace_word_hyphens$LAYOUT;
    }

    private static final long replace_word_hyphens$OFFSET = 28;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool replace_word_hyphens
     * }
     */
    public static final long replace_word_hyphens$offset() {
        return replace_word_hyphens$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool replace_word_hyphens
     * }
     */
    public static boolean replace_word_hyphens(MemorySegment struct) {
        return struct.get(replace_word_hyphens$LAYOUT, replace_word_hyphens$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool replace_word_hyphens
     * }
     */
    public static void replace_word_hyphens(MemorySegment struct, boolean fieldValue) {
        struct.set(replace_word_hyphens$LAYOUT, replace_word_hyphens$OFFSET, fieldValue);
    }

    private static final OfBoolean delete_word_hyphens$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("delete_word_hyphens"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool delete_word_hyphens
     * }
     */
    public static final OfBoolean delete_word_hyphens$layout() {
        return delete_word_hyphens$LAYOUT;
    }

    private static final long delete_word_hyphens$OFFSET = 29;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool delete_word_hyphens
     * }
     */
    public static final long delete_word_hyphens$offset() {
        return delete_word_hyphens$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool delete_word_hyphens
     * }
     */
    public static boolean delete_word_hyphens(MemorySegment struct) {
        return struct.get(delete_word_hyphens$LAYOUT, delete_word_hyphens$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool delete_word_hyphens
     * }
     */
    public static void delete_word_hyphens(MemorySegment struct, boolean fieldValue) {
        struct.set(delete_word_hyphens$LAYOUT, delete_word_hyphens$OFFSET, fieldValue);
    }

    private static final OfBoolean delete_final_periods$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("delete_final_periods"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool delete_final_periods
     * }
     */
    public static final OfBoolean delete_final_periods$layout() {
        return delete_final_periods$LAYOUT;
    }

    private static final long delete_final_periods$OFFSET = 30;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool delete_final_periods
     * }
     */
    public static final long delete_final_periods$offset() {
        return delete_final_periods$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool delete_final_periods
     * }
     */
    public static boolean delete_final_periods(MemorySegment struct) {
        return struct.get(delete_final_periods$LAYOUT, delete_final_periods$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool delete_final_periods
     * }
     */
    public static void delete_final_periods(MemorySegment struct, boolean fieldValue) {
        struct.set(delete_final_periods$LAYOUT, delete_final_periods$OFFSET, fieldValue);
    }

    private static final OfBoolean delete_acronym_periods$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("delete_acronym_periods"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool delete_acronym_periods
     * }
     */
    public static final OfBoolean delete_acronym_periods$layout() {
        return delete_acronym_periods$LAYOUT;
    }

    private static final long delete_acronym_periods$OFFSET = 31;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool delete_acronym_periods
     * }
     */
    public static final long delete_acronym_periods$offset() {
        return delete_acronym_periods$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool delete_acronym_periods
     * }
     */
    public static boolean delete_acronym_periods(MemorySegment struct) {
        return struct.get(delete_acronym_periods$LAYOUT, delete_acronym_periods$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool delete_acronym_periods
     * }
     */
    public static void delete_acronym_periods(MemorySegment struct, boolean fieldValue) {
        struct.set(delete_acronym_periods$LAYOUT, delete_acronym_periods$OFFSET, fieldValue);
    }

    private static final OfBoolean drop_english_possessives$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("drop_english_possessives"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool drop_english_possessives
     * }
     */
    public static final OfBoolean drop_english_possessives$layout() {
        return drop_english_possessives$LAYOUT;
    }

    private static final long drop_english_possessives$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool drop_english_possessives
     * }
     */
    public static final long drop_english_possessives$offset() {
        return drop_english_possessives$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool drop_english_possessives
     * }
     */
    public static boolean drop_english_possessives(MemorySegment struct) {
        return struct.get(drop_english_possessives$LAYOUT, drop_english_possessives$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool drop_english_possessives
     * }
     */
    public static void drop_english_possessives(MemorySegment struct, boolean fieldValue) {
        struct.set(drop_english_possessives$LAYOUT, drop_english_possessives$OFFSET, fieldValue);
    }

    private static final OfBoolean delete_apostrophes$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("delete_apostrophes"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool delete_apostrophes
     * }
     */
    public static final OfBoolean delete_apostrophes$layout() {
        return delete_apostrophes$LAYOUT;
    }

    private static final long delete_apostrophes$OFFSET = 33;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool delete_apostrophes
     * }
     */
    public static final long delete_apostrophes$offset() {
        return delete_apostrophes$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool delete_apostrophes
     * }
     */
    public static boolean delete_apostrophes(MemorySegment struct) {
        return struct.get(delete_apostrophes$LAYOUT, delete_apostrophes$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool delete_apostrophes
     * }
     */
    public static void delete_apostrophes(MemorySegment struct, boolean fieldValue) {
        struct.set(delete_apostrophes$LAYOUT, delete_apostrophes$OFFSET, fieldValue);
    }

    private static final OfBoolean expand_numex$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("expand_numex"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool expand_numex
     * }
     */
    public static final OfBoolean expand_numex$layout() {
        return expand_numex$LAYOUT;
    }

    private static final long expand_numex$OFFSET = 34;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool expand_numex
     * }
     */
    public static final long expand_numex$offset() {
        return expand_numex$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool expand_numex
     * }
     */
    public static boolean expand_numex(MemorySegment struct) {
        return struct.get(expand_numex$LAYOUT, expand_numex$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool expand_numex
     * }
     */
    public static void expand_numex(MemorySegment struct, boolean fieldValue) {
        struct.set(expand_numex$LAYOUT, expand_numex$OFFSET, fieldValue);
    }

    private static final OfBoolean roman_numerals$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("roman_numerals"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool roman_numerals
     * }
     */
    public static final OfBoolean roman_numerals$layout() {
        return roman_numerals$LAYOUT;
    }

    private static final long roman_numerals$OFFSET = 35;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool roman_numerals
     * }
     */
    public static final long roman_numerals$offset() {
        return roman_numerals$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool roman_numerals
     * }
     */
    public static boolean roman_numerals(MemorySegment struct) {
        return struct.get(roman_numerals$LAYOUT, roman_numerals$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool roman_numerals
     * }
     */
    public static void roman_numerals(MemorySegment struct, boolean fieldValue) {
        struct.set(roman_numerals$LAYOUT, roman_numerals$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

