// Generated by jextract

package kid_meier.libpostal4j.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct libpostal_address_parser_response {
 *     size_t num_components;
 *     char **components;
 *     char **labels;
 * }
 * }
 */
public class libpostal_address_parser_response {

    libpostal_address_parser_response() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        libpostal_h.C_LONG.withName("num_components"),
        libpostal_h.C_POINTER.withName("components"),
        libpostal_h.C_POINTER.withName("labels")
    ).withName("libpostal_address_parser_response");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong num_components$LAYOUT = (OfLong)$LAYOUT.select(groupElement("num_components"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t num_components
     * }
     */
    public static final OfLong num_components$layout() {
        return num_components$LAYOUT;
    }

    private static final long num_components$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t num_components
     * }
     */
    public static final long num_components$offset() {
        return num_components$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t num_components
     * }
     */
    public static long num_components(MemorySegment struct) {
        return struct.get(num_components$LAYOUT, num_components$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t num_components
     * }
     */
    public static void num_components(MemorySegment struct, long fieldValue) {
        struct.set(num_components$LAYOUT, num_components$OFFSET, fieldValue);
    }

    private static final AddressLayout components$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("components"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char **components
     * }
     */
    public static final AddressLayout components$layout() {
        return components$LAYOUT;
    }

    private static final long components$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char **components
     * }
     */
    public static final long components$offset() {
        return components$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char **components
     * }
     */
    public static MemorySegment components(MemorySegment struct) {
        return struct.get(components$LAYOUT, components$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char **components
     * }
     */
    public static void components(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(components$LAYOUT, components$OFFSET, fieldValue);
    }

    private static final AddressLayout labels$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("labels"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char **labels
     * }
     */
    public static final AddressLayout labels$layout() {
        return labels$LAYOUT;
    }

    private static final long labels$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char **labels
     * }
     */
    public static final long labels$offset() {
        return labels$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char **labels
     * }
     */
    public static MemorySegment labels(MemorySegment struct) {
        return struct.get(labels$LAYOUT, labels$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char **labels
     * }
     */
    public static void labels(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(labels$LAYOUT, labels$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

