// Generated by jextract

package kid_meier.libpostal4j.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct libpostal_normalized_token {
 *     char *str;
 *     libpostal_token_t token;
 * }
 * }
 */
public class libpostal_normalized_token {

    libpostal_normalized_token() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        libpostal_h.C_POINTER.withName("str"),
        libpostal_token.layout().withName("token")
    ).withName("libpostal_normalized_token");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout str$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("str"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *str
     * }
     */
    public static final AddressLayout str$layout() {
        return str$LAYOUT;
    }

    private static final long str$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *str
     * }
     */
    public static final long str$offset() {
        return str$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *str
     * }
     */
    public static MemorySegment str(MemorySegment struct) {
        return struct.get(str$LAYOUT, str$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *str
     * }
     */
    public static void str(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(str$LAYOUT, str$OFFSET, fieldValue);
    }

    private static final GroupLayout token$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("token"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * libpostal_token_t token
     * }
     */
    public static final GroupLayout token$layout() {
        return token$LAYOUT;
    }

    private static final long token$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * libpostal_token_t token
     * }
     */
    public static final long token$offset() {
        return token$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * libpostal_token_t token
     * }
     */
    public static MemorySegment token(MemorySegment struct) {
        return struct.asSlice(token$OFFSET, token$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * libpostal_token_t token
     * }
     */
    public static void token(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, token$OFFSET, token$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

