// Generated by jextract

package kid_meier.libpostal4j.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct libpostal_token {
 *     size_t offset;
 *     size_t len;
 *     uint16_t type;
 * } libpostal_token_t
 * }
 */
public class libpostal_token_t extends libpostal_token {

    libpostal_token_t() {
        // Should not be called directly
    }
}

