// Generated by jextract

package kid_meier.libpostal4j.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct libpostal_normalize_options {
 *     char **languages;
 *     size_t num_languages;
 *     uint16_t address_components;
 *     _Bool latin_ascii;
 *     _Bool transliterate;
 *     _Bool strip_accents;
 *     _Bool decompose;
 *     _Bool lowercase;
 *     _Bool trim_string;
 *     _Bool drop_parentheticals;
 *     _Bool replace_numeric_hyphens;
 *     _Bool delete_numeric_hyphens;
 *     _Bool split_alpha_from_numeric;
 *     _Bool replace_word_hyphens;
 *     _Bool delete_word_hyphens;
 *     _Bool delete_final_periods;
 *     _Bool delete_acronym_periods;
 *     _Bool drop_english_possessives;
 *     _Bool delete_apostrophes;
 *     _Bool expand_numex;
 *     _Bool roman_numerals;
 * } libpostal_normalize_options_t
 * }
 */
public class libpostal_normalize_options_t extends libpostal_normalize_options {

    libpostal_normalize_options_t() {
        // Should not be called directly
    }
}

