// Generated by jextract

package kid_meier.libpostal4j.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct libpostal_near_dupe_hash_options {
 *     _Bool with_name;
 *     _Bool with_address;
 *     _Bool with_unit;
 *     _Bool with_city_or_equivalent;
 *     _Bool with_small_containing_boundaries;
 *     _Bool with_postal_code;
 *     _Bool with_latlon;
 *     double latitude;
 *     double longitude;
 *     uint32_t geohash_precision;
 *     _Bool name_and_address_keys;
 *     _Bool name_only_keys;
 *     _Bool address_only_keys;
 * }
 * }
 */
public class libpostal_near_dupe_hash_options {

    libpostal_near_dupe_hash_options() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        libpostal_h.C_BOOL.withName("with_name"),
        libpostal_h.C_BOOL.withName("with_address"),
        libpostal_h.C_BOOL.withName("with_unit"),
        libpostal_h.C_BOOL.withName("with_city_or_equivalent"),
        libpostal_h.C_BOOL.withName("with_small_containing_boundaries"),
        libpostal_h.C_BOOL.withName("with_postal_code"),
        libpostal_h.C_BOOL.withName("with_latlon"),
        MemoryLayout.paddingLayout(1),
        libpostal_h.C_DOUBLE.withName("latitude"),
        libpostal_h.C_DOUBLE.withName("longitude"),
        libpostal_h.C_INT.withName("geohash_precision"),
        libpostal_h.C_BOOL.withName("name_and_address_keys"),
        libpostal_h.C_BOOL.withName("name_only_keys"),
        libpostal_h.C_BOOL.withName("address_only_keys"),
        MemoryLayout.paddingLayout(1)
    ).withName("libpostal_near_dupe_hash_options");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfBoolean with_name$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("with_name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool with_name
     * }
     */
    public static final OfBoolean with_name$layout() {
        return with_name$LAYOUT;
    }

    private static final long with_name$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool with_name
     * }
     */
    public static final long with_name$offset() {
        return with_name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool with_name
     * }
     */
    public static boolean with_name(MemorySegment struct) {
        return struct.get(with_name$LAYOUT, with_name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool with_name
     * }
     */
    public static void with_name(MemorySegment struct, boolean fieldValue) {
        struct.set(with_name$LAYOUT, with_name$OFFSET, fieldValue);
    }

    private static final OfBoolean with_address$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("with_address"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool with_address
     * }
     */
    public static final OfBoolean with_address$layout() {
        return with_address$LAYOUT;
    }

    private static final long with_address$OFFSET = 1;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool with_address
     * }
     */
    public static final long with_address$offset() {
        return with_address$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool with_address
     * }
     */
    public static boolean with_address(MemorySegment struct) {
        return struct.get(with_address$LAYOUT, with_address$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool with_address
     * }
     */
    public static void with_address(MemorySegment struct, boolean fieldValue) {
        struct.set(with_address$LAYOUT, with_address$OFFSET, fieldValue);
    }

    private static final OfBoolean with_unit$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("with_unit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool with_unit
     * }
     */
    public static final OfBoolean with_unit$layout() {
        return with_unit$LAYOUT;
    }

    private static final long with_unit$OFFSET = 2;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool with_unit
     * }
     */
    public static final long with_unit$offset() {
        return with_unit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool with_unit
     * }
     */
    public static boolean with_unit(MemorySegment struct) {
        return struct.get(with_unit$LAYOUT, with_unit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool with_unit
     * }
     */
    public static void with_unit(MemorySegment struct, boolean fieldValue) {
        struct.set(with_unit$LAYOUT, with_unit$OFFSET, fieldValue);
    }

    private static final OfBoolean with_city_or_equivalent$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("with_city_or_equivalent"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool with_city_or_equivalent
     * }
     */
    public static final OfBoolean with_city_or_equivalent$layout() {
        return with_city_or_equivalent$LAYOUT;
    }

    private static final long with_city_or_equivalent$OFFSET = 3;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool with_city_or_equivalent
     * }
     */
    public static final long with_city_or_equivalent$offset() {
        return with_city_or_equivalent$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool with_city_or_equivalent
     * }
     */
    public static boolean with_city_or_equivalent(MemorySegment struct) {
        return struct.get(with_city_or_equivalent$LAYOUT, with_city_or_equivalent$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool with_city_or_equivalent
     * }
     */
    public static void with_city_or_equivalent(MemorySegment struct, boolean fieldValue) {
        struct.set(with_city_or_equivalent$LAYOUT, with_city_or_equivalent$OFFSET, fieldValue);
    }

    private static final OfBoolean with_small_containing_boundaries$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("with_small_containing_boundaries"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool with_small_containing_boundaries
     * }
     */
    public static final OfBoolean with_small_containing_boundaries$layout() {
        return with_small_containing_boundaries$LAYOUT;
    }

    private static final long with_small_containing_boundaries$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool with_small_containing_boundaries
     * }
     */
    public static final long with_small_containing_boundaries$offset() {
        return with_small_containing_boundaries$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool with_small_containing_boundaries
     * }
     */
    public static boolean with_small_containing_boundaries(MemorySegment struct) {
        return struct.get(with_small_containing_boundaries$LAYOUT, with_small_containing_boundaries$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool with_small_containing_boundaries
     * }
     */
    public static void with_small_containing_boundaries(MemorySegment struct, boolean fieldValue) {
        struct.set(with_small_containing_boundaries$LAYOUT, with_small_containing_boundaries$OFFSET, fieldValue);
    }

    private static final OfBoolean with_postal_code$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("with_postal_code"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool with_postal_code
     * }
     */
    public static final OfBoolean with_postal_code$layout() {
        return with_postal_code$LAYOUT;
    }

    private static final long with_postal_code$OFFSET = 5;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool with_postal_code
     * }
     */
    public static final long with_postal_code$offset() {
        return with_postal_code$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool with_postal_code
     * }
     */
    public static boolean with_postal_code(MemorySegment struct) {
        return struct.get(with_postal_code$LAYOUT, with_postal_code$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool with_postal_code
     * }
     */
    public static void with_postal_code(MemorySegment struct, boolean fieldValue) {
        struct.set(with_postal_code$LAYOUT, with_postal_code$OFFSET, fieldValue);
    }

    private static final OfBoolean with_latlon$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("with_latlon"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool with_latlon
     * }
     */
    public static final OfBoolean with_latlon$layout() {
        return with_latlon$LAYOUT;
    }

    private static final long with_latlon$OFFSET = 6;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool with_latlon
     * }
     */
    public static final long with_latlon$offset() {
        return with_latlon$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool with_latlon
     * }
     */
    public static boolean with_latlon(MemorySegment struct) {
        return struct.get(with_latlon$LAYOUT, with_latlon$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool with_latlon
     * }
     */
    public static void with_latlon(MemorySegment struct, boolean fieldValue) {
        struct.set(with_latlon$LAYOUT, with_latlon$OFFSET, fieldValue);
    }

    private static final OfDouble latitude$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("latitude"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double latitude
     * }
     */
    public static final OfDouble latitude$layout() {
        return latitude$LAYOUT;
    }

    private static final long latitude$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double latitude
     * }
     */
    public static final long latitude$offset() {
        return latitude$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double latitude
     * }
     */
    public static double latitude(MemorySegment struct) {
        return struct.get(latitude$LAYOUT, latitude$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double latitude
     * }
     */
    public static void latitude(MemorySegment struct, double fieldValue) {
        struct.set(latitude$LAYOUT, latitude$OFFSET, fieldValue);
    }

    private static final OfDouble longitude$LAYOUT = (OfDouble)$LAYOUT.select(groupElement("longitude"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * double longitude
     * }
     */
    public static final OfDouble longitude$layout() {
        return longitude$LAYOUT;
    }

    private static final long longitude$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * double longitude
     * }
     */
    public static final long longitude$offset() {
        return longitude$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * double longitude
     * }
     */
    public static double longitude(MemorySegment struct) {
        return struct.get(longitude$LAYOUT, longitude$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * double longitude
     * }
     */
    public static void longitude(MemorySegment struct, double fieldValue) {
        struct.set(longitude$LAYOUT, longitude$OFFSET, fieldValue);
    }

    private static final OfInt geohash_precision$LAYOUT = (OfInt)$LAYOUT.select(groupElement("geohash_precision"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t geohash_precision
     * }
     */
    public static final OfInt geohash_precision$layout() {
        return geohash_precision$LAYOUT;
    }

    private static final long geohash_precision$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t geohash_precision
     * }
     */
    public static final long geohash_precision$offset() {
        return geohash_precision$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t geohash_precision
     * }
     */
    public static int geohash_precision(MemorySegment struct) {
        return struct.get(geohash_precision$LAYOUT, geohash_precision$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t geohash_precision
     * }
     */
    public static void geohash_precision(MemorySegment struct, int fieldValue) {
        struct.set(geohash_precision$LAYOUT, geohash_precision$OFFSET, fieldValue);
    }

    private static final OfBoolean name_and_address_keys$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("name_and_address_keys"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool name_and_address_keys
     * }
     */
    public static final OfBoolean name_and_address_keys$layout() {
        return name_and_address_keys$LAYOUT;
    }

    private static final long name_and_address_keys$OFFSET = 28;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool name_and_address_keys
     * }
     */
    public static final long name_and_address_keys$offset() {
        return name_and_address_keys$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool name_and_address_keys
     * }
     */
    public static boolean name_and_address_keys(MemorySegment struct) {
        return struct.get(name_and_address_keys$LAYOUT, name_and_address_keys$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool name_and_address_keys
     * }
     */
    public static void name_and_address_keys(MemorySegment struct, boolean fieldValue) {
        struct.set(name_and_address_keys$LAYOUT, name_and_address_keys$OFFSET, fieldValue);
    }

    private static final OfBoolean name_only_keys$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("name_only_keys"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool name_only_keys
     * }
     */
    public static final OfBoolean name_only_keys$layout() {
        return name_only_keys$LAYOUT;
    }

    private static final long name_only_keys$OFFSET = 29;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool name_only_keys
     * }
     */
    public static final long name_only_keys$offset() {
        return name_only_keys$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool name_only_keys
     * }
     */
    public static boolean name_only_keys(MemorySegment struct) {
        return struct.get(name_only_keys$LAYOUT, name_only_keys$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool name_only_keys
     * }
     */
    public static void name_only_keys(MemorySegment struct, boolean fieldValue) {
        struct.set(name_only_keys$LAYOUT, name_only_keys$OFFSET, fieldValue);
    }

    private static final OfBoolean address_only_keys$LAYOUT = (OfBoolean)$LAYOUT.select(groupElement("address_only_keys"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * _Bool address_only_keys
     * }
     */
    public static final OfBoolean address_only_keys$layout() {
        return address_only_keys$LAYOUT;
    }

    private static final long address_only_keys$OFFSET = 30;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * _Bool address_only_keys
     * }
     */
    public static final long address_only_keys$offset() {
        return address_only_keys$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * _Bool address_only_keys
     * }
     */
    public static boolean address_only_keys(MemorySegment struct) {
        return struct.get(address_only_keys$LAYOUT, address_only_keys$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * _Bool address_only_keys
     * }
     */
    public static void address_only_keys(MemorySegment struct, boolean fieldValue) {
        struct.set(address_only_keys$LAYOUT, address_only_keys$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

